# Site settings

title: ~mbroggy
email: mbroggy@gmail.com
description: Michael Broggy's project site, updated as and when I remember...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mbroggy.github.io/" # the base hostname & protocol for your site
twitter_username: simparri
github_username:  mbroggy

# Build settings

markdown: kramdown
paginate: 5
